name: "Set Up Python Environment"

inputs:
  python-version:
    description: "Python version to use"
    required: true

runs:
  using: composite
  steps:
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5.3.1
      with:
        version: "0.6.6"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Install project and dependencies
      run: uv sync --frozen --dev
      shell: bash
