import jwt

from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from passlib.context import CryptContext
from pydantic import BaseModel
from datetime import timedelta, datetime, timezone
from .config import env_vars

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

oauth2_scheme = OAuth2PasswordBearer(
    tokenUrl="token",
    # We are using scope to sideload info on the end user. So "enduser" here is just a placeholder, but the actual username will be passed by the frontend.
    scopes={"enduser": "end user to act as (a valid username), if frontend"},
)


class Token(BaseModel):
    access_token: str
    token_type: str


class TokenData(BaseModel):
    username: str | None = None


def verify_password(plain_password: str, hashed_password: str):
    revert_hash = hashed_password.replace("$2y", "$2b", 1)
    return pwd_context.verify(plain_password, revert_hash)


def get_password_hash(password: str):
    # to align with the password hashing used by Laravel, we have to replace the 2b generated by pwd_context with 2y and that should be the version we store.
    # They should be functionally the same: https://stackoverflow.com/a/36225192/28478909
    initial_hash = pwd_context.hash(password)
    return initial_hash.replace("$2b", "$2y", 1)


def create_access_token(data: dict, expires_delta: timedelta | None = None):
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.now(timezone.utc) + expires_delta
    else:
        expire = datetime.now(timezone.utc) + timedelta(
            minutes=env_vars["ACCESS_TOKEN_EXPIRE_MINUTES"]
        )
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(
        to_encode, env_vars["SECRET_KEY"], algorithm=env_vars["ALGORITHM"]
    )
    return encoded_jwt
