FROM mcr.microsoft.com/devcontainers/python:3.10-bookworm

# Copy uv and uvx from the official image
COPY --from=ghcr.io/astral-sh/uv:0.4.30 /uv /uvx /bin/

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy
