name: style

on:
  pull_request:  # any pull request

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.10"
      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@v45.0.1
        with:
          files: |
            **.py
            **.ipynb
      - name: Run linter
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          uv tool run ruff check --diff ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Run formatter
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          uv tool run ruff format --diff ${{ steps.changed-files.outputs.all_changed_files }}
